### ISSUE TITLE
question: adding custom proxy traps in class constructors and instances

### ISSUE THREAD

**Issue by mwaqar666** [typestack/typedi#1107]
**Scenario:**
While adding dependencies manually and then injecting them somewhere else using the following approach works 
```typescript
import { Container, Token } from "typedi";

const ControllerToken = new Token<?>("ControllerName");
const ServiceToken = new Token<?>("ServiceName");

class Controller {
  public constructor (
    // Injecting service here
    @Inject(ServiceToken) private readonly serviceInstance: Service
  ) {}
}

class Service {
  //
}

// Register them somewhere
Container.set(ControllerToken, Controller);
Container.set(ServiceToken, Service);

// Retrieve them somewhere else
const controllerInstance = Container.get(ControllerToken); // Controller instance retrieved with service instance also resolved
```

**The problem:**
When I tweak the `Controller` class a little bit by adding a custom decorator that traps the class instantiation and property accessing like this:

```typescript
const Controller = <T extends object>(target: Constructable<T, Array<any>>): Constructable<T, Array<any>> => {
  /**
   * Trap the class instantiation, so when an instance of the class is created, we add another trap on property accessor
   */
  return new Proxy(target, {
    construct(concreteController: Constructable<T, any>, argumentsArray: Array<any>): T {
      const controllerInstance: T = Reflect.construct(concreteController, argumentsArray);

      /**
       * After the instance is created, we add another trap for property accessor
       */
      return new Proxy(controllerInstance, {
        get(controller: T, property: string): T[Key<T>] {
          const targetProp: T[Key<T>] = Reflect.get(controller, property);

          /**
           * We check if the property being accessed is a class method, if so, we
           * bind the "this" context of method to class instance itself. This way
           * we can pass around the method signature as callback to another function
           */

          if (targetProp instanceof Function) {
            return targetProp.bind(controller);
          }

          return targetProp;
        },
      });
    },
  });
};

@Controller
class Controller {
  //...
```

Then the `Service` class is not resolved in the `Controller` class instance and instead I get `ContainerInstance` injected.

Is this the expected behavior or is there any workaround for this?

**Comment by freshgum-bubbles** [comment]
This might be because TypeDI isn't able to resolve the dependencies from the Proxy,
as it's effectively masking your actual constructor implementation.
In this case, when `Reflect.getMetadata` is called upon your proxy, the reflective key
the `@Inject` decorator uses to store any requested dependencies on your actual
class aren't visible to TypeDI anymore.

A quick hack would be to call [Reflect.ownKeys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/ownKeys) on your 
target class, and manually copy them to the `Proxy` instance.  
However, I don't believe this would work very well when your class is extended,
as you would still be masking keys placed on the upstream class.

You might be better served by using a factory or, alternatively, creating a method
decorator that calls `.bind` on each method.
