### ISSUE TITLE
question: mixing global with non-global services

### ISSUE THREAD

**Issue by ramiel** [typestack/typedi#219]
Let's consider this situation in which I have a service A that can be global. I also have a service B which must be scoped, i.e. a different instance for each request. Service A depends on service B.

```ts
@Service({global: true})
class A {
   @Inject()
   private readonly b!: B
}

// somewhere else
const container = Container.of(req.id)
container.set(B, new B());

// somewhere else
const a = container.get(A)
```

My question is: what instance of B will be used in A? Everytime a different one or each time the same instantiated the first time?

**Comment by NoNameProvided** [comment]
If your service is global it means, it will be always requested from the default (global) container. When a non-global service is requested the lib first checks if it exists in the current container and if not, it will request the metadata from the default container, create and cache an instance in the scoped container.

In your specific example, the following happens:
- service metadata is registered for the service `A` (always global)
- an empty scoped container is created with `req.id`
- you set `new B()` as __value__ for token `B` in scoped container
- you request `A` from the scoped container
  - it gets the metadata and sees the service is global
  - __from here two things happen detailed below__

If this is the __first time you request `A`__ then `A` will be initialized from the global container with `B` from the scoped container.
If this is the __second or more time you request__ `A` then `A` value exists already in the global container (with `B` set from the first scoped container) and the value is immediately returned, so the service `A` will use `B` from the first scoped container which requested `A` and not the currently provided `B` from the currently used scoped container.

> I also have a service B which must be scoped, i.e. a different instance for each request.

You can use the `transient` option instead of your current approach to request a new instance from the container every time for a given service. So you don't need to create a new container just for that. 

You can see the current implementation here: 

https://github.com/typestack/typedi/blob/da50666e1f1b40e3d214a945880f8c31c24a974b/src/container-instance.class.ts#L47-L76

PS: Container inheritance will be reworked later and the above-described behavior will change.

**Comment by ramiel** [comment]
Thank you, it's prerfectly clear. What it's not clear now is how to use a transient Service and how it works :) Is it my fault or I can't find the relative documentation?

Also, if the class is not defined by me, I find easier to add the service to the container through `set`: can I, in that case, mark is as transient? If it's possible to set a Service as transient only through the @Service directive, how can I handle an external class?

**Comment by ramiel** [comment]
Oh, anyway, I cannot use a transient service. I'm actually talking of an ORM that needs to be the same instance for the duration of the request, but different in a new request, so probably the transient option is not the best, isn't it?

**Comment by NoNameProvided** [comment]
> Oh, anyway, I cannot use a transient service. I'm actually talking of an ORM that needs to be the same instance for the duration of the request, but different in a new request, so probably the transient option is not the best, isn't it?

Yes, in that case, transient service won't work for you, but you can use your original approach without marking service A as global. In that case for every request, the created scoped container will create an instance of `A` and `B`. (I know in the original example you wanted to `A` to be created only once.) Alternatively, if your logic allows you can turn the injection direction around and request `A` from `B`. That way B will be always created once and it will always inject the same global `A` class instance.
