### ISSUE TITLE
How do we share a service across an NPM package?

### ISSUE THREAD

**Issue by IAMtheIAM** [typestack/typedi#288]
**I was trying to...**
Create a shared service decorated using @Service which is published in an npm package (pure TypeScript source). Then I import the decorated class from my consuming repo and try to inject it. 

**The problem:**
However, it results in "ServiceNotFoundError".
I think the problem is that typedi is making two separate containers, one in my npm package, another in the consuming repo.

Is there a way to get typedi to share one container across npm packages and sources?

V0.9.1

**Comment by NoNameProvided** [comment]
> I think the problem is that typedi is making two separate containers, one in my npm package, another in the consuming repo.

You are right that is the root cause of this issue. What you experience can be solved by dependency flattening. For more info about why this happens can be found in this comment: https://github.com/typestack/class-validator/issues/261#issuecomment-435705783. 

For NPM to flatten your dependencies you need to make sure the following criteria are met:
- you (and your possible teammates) uses a new NPM or Yarn version (latest is best)
- the typedi package uses the correct version in both packages
  - either it is pinned to the exact same version 
  - or if a relaxed version range is added (eg: `^0.9.0`) then both packages can resolve the same latest version
- re-install your node_modules (aka `rm -rf node_modules package-lock.json` and then `npm install`) 

If you are using NPM but you don't control the package.json of your two projects you can try the safe command of `npm dedupe` to flatten your node_modules and can add it as your post-install script. 

If none of the above works, you can try the nuclear option of flatting with the `flatten-packages` package which forcefully dedupes your node_modules. (Not advised, can mess up node_modules.)
