### ISSUE TITLE
Injecting a service into another service

### ISSUE THREAD

**Issue by robenson-dev** [typestack/typedi#413]
### Description

I have a big problem with `typedi` so i want to inject a other service into my code 

```ts
import { ChannelService } from ".";
import { Media } from "../entity";

const channelService = new ChannelService();

@Service()
export class MediaService {

  @InjectRepository()
  protected mediaRepository: MediaRepository;

  @Inject('ChannelService')
  protected channelService: ChannelService;

  async createMediaService(file: FileUpload, userId: string): Promise<Media>{
    const mediaUpload = await uploadFile(file);
    // channel is undefined
    const channel = await channelService.getUserChannel(userId);
    console.log(userId, channel);
    
    return await this.mediaRepository.save({...mediaUpload, channel: channel});
  }
```

**Comment by AdamManuel-dev** [comment]
Pretty sure you can use `this.channelService.getUserChannel(userId);` instead of `channelService.getUserChannel(userId);`

It would probably help you debug if you renamed either `const channelService = new ChannelService();` or `this.channelService.getUserChannel(userId);` so that they are not the same.

**Comment by NoNameProvided** [comment]
The problem you face is not clear enough for me to help. If you still encounter this problem please open a new ticket with a detailed description of what you are trying to achieve, what is happening and what would you expect to happen.
