### ISSUE TITLE
How it is supposed to work with unit test?

### ISSUE THREAD

**Issue by hellraisercenobit** [typestack/typedi#45]
Hello there,
I would like to test my controller (routing-controllers) but i don't really know how to.
Typedi is supposed to work like Angular2+ inject or similar.
But when i use Container.set to override my model's method used by the controller it's seems to be broken.
I need some hint to know how to do that.
I think i do not test my controller like expected or maybe i don't really understand Typedi Container and @Service injection  implementation.
It's supposed to be usefull to avoid to mock db connection.

Thx a lot.

My spec

```
import 'reflect-metadata';
import { Application } from 'express';
import request from 'supertest';
import { createExpressServer, useContainer as useContainerRouting } from 'routing-controllers';
import { Container } from 'typedi';
import { ExampleController } from '../controllers/example.controller';
import { ExampleRepository } from '../repositories/example.repository';
import { ExampleModel } from '../models/example.model';

describe('GET', () => {
  let app: Application | null;

  beforeEach((_done: jest.DoneCallback) => {
    useContainerRouting(Container);
  });

  afterEach((_done: jest.DoneCallback) => {
    Container.reset();
    app = null;
  });

  it('should call model with proper id and returns model response', async () => {
    const EXAMPLE_ID_TEST: number = 1;

    app = createExpressServer({
      cors: true,
      controllers: [
        ExampleController
      ]
    });

    @Service()
    class TestModel {
      public getExampleById: any = jest.fn().mockImplementation((_id: number) => new Promise((resolve: any) => resolve({})));
    }

    Container.set(ExampleModel, new TestModel());

    const res: request.Response = await request(app).get(`/example/${EXAMPLE_ID_TEST}`);

    expect(res.body).toEqual({});
});
```

My controller

```
import { ExampleModel } from '../models/example.model';
import { TableTest } from '../entities/tabletest.entity';
import { JsonController, Get } from 'routing-controllers';

@JsonController('/example')
export class ExampleController {
  constructor(
    private readonly model: ExampleModel) {
  }
  @Get('/:id')
  public async getExample(@Param('id') id: number): Promise<TableTest> {
    return this.model.getExampleById(id);
  }
}
```

My Model

```
import { TableTest } from '../entities/tabletest.entity';
import { Service } from 'typedi';
import { OrmRepository } from 'typeorm-typedi-extensions';
import { NotFoundError } from 'routing-controllers';
import { ExampleRepository } from '../repositories/example.repository';

@Service()
export class ExampleModel {
  constructor(
    @OrmRepository()
    private readonly repository: ExampleRepository) {
  }

  public async getExampleById(id: number): Promise<TableTest> {
    const example: TableTest | undefined = await this.repository.findOneById(id);

    if (example === undefined) {
      throw new NotFoundError(`Example ${id} not found`);
    }

    return example;
  }
}
```

**Comment by pleerock** [comment]
@19majkel94 I think you have experience mocking things using typedi and `@OrmRepository()`, can you help on this topic?

**Comment by gmongin** [comment]
After some new tests, i got this error:

Cannot determine a class of the requesting service \"undefined\""

It's like my preset Service is not set correctly.

So, if i mock completely my model, the repo is supposed to never been called and never instantiate.
Then @OrmRepository() will never been called.

**Comment by gmongin** [comment]
It is possible to override a service before createExpressService?

**Comment by 19majkel94** [comment]
General rule of thumb - keep it simple, stupid! 😉 

Constructor injection in controllers is the best because it's DI framework agnostic - you can just create the instance of the class and provide your mocks by yourself:
```ts
    let companyController: CompanyController;
    let bodyMock: ICategory;
    beforeEach(() => {
        companyController = new CompanyController(companyRepositoryMock, new Validator());
        bodyMock = new ICategory();
    });
```
So you make unit test of your controller methods like they would be the services, not connected to http (thanks to routing-controllers decorators). You check all the code flow in unit tests.
```ts
it("should login successfully when credentials are ok", async () => {
    const reponse: string = await userControler.loginUser(sessionMock, bodyMock);
    expect(reponse).to.equals("Logged succesfully!");
    expect(sessionMock.user.email).to.equals(bodyMock.email);
});
```

Then, you can make integration test. They check if the http server really works and return correct response:
```ts
it("should respond with 400 BadRequest when password is wrong", async () => {
    const credentials = {
        email: "test@test.pl",
        password: "wrongPassword"
    };
    const response = await catchBadResponse(
        chai.request(app)
            .post("/api/user/login")
            .send(credentials)
    );

    expect(response).to.have.status(400);
    expect(response.body.message).to.equals("Wrong email or password!");
});
````
In integration test you can't mock your code parts like services, etc. You need to check if all of your apps parts are working together. You check only the one good scenario that use all of the apps parts.

The only thing you should do is to to connect to local testing database, seed it with test data and maybe restore after each test that modified it. Mocks are allowed only to 3rd-party services like mail or Amazon S3 and I could be easily done with `container.set` or at the environment level (proxy server?).

So, @gmongin, don't try to mock all the world when you are making http request to your app because you will test your mocks, not the real code 😆

**Comment by gmongin** [comment]
@19majkel94 thx for the reply.

You misunderstood my real target on this post.
My question wasn't on "how to do unit test" but how to override some class/service with Typedi like Angular2+ TestBed way.
Of course i don't wanna UT with a real DB it's just a non sense we are ok with this, it's more than a concern of IT.
With your approach i couldn't test my controller but just the method linked to my specific route.
For example, with supertest i'm able to mock an expressApp to test my controller.
So i'm thinking at the begining, i will be able to declare new Class to replace my service/model (like overriding providers with angular) with typedi containers inside my controller to avoid db call with repository and to have an efficient way to test completly my controller with validation decorators etc....

So, it's possible or not? :)

If it's not with typedi, i'm ok on this no problem, but it could be really cool to support this kind of approach to have more flexibility.

Sorry if i wasn't really clear on my post.

**Comment by 19majkel94** [comment]
I understood your question:
> I would like to test my controller (routing-controllers) but i don't really know how to.

So I said how to to this 😉 
Routing-controllers provides you great abstraction over express/koa/http, so you can test your controllers action handlers just like services - they are like pure function that takes the input (eg. id and token) and produce the result (entity from db). There's really no need to "mock an expressApp to test my controller with supertest", you can do it much more simplier than with pure express req-res apps.

> maybe i don't really understand Typedi Container and @service injection implementation.

`@Service` inform TypeDI to peform DI on this class whenever someone calls `Container.get(TheClass)`. So you don't need to do:
```ts
@Service()
    class TestModel {
      public getExampleById: any = jest.fn().mockImplementation((_id: number) => new Promise((resolve: any) => resolve({})));
    }
```
inside `before` in your tests because `ExampleModel` is the injection token. The only thing to do is to:
```ts
Container.set(ExampleModel, new TestModel());
```
So all `ExampleModel` injection into services/models/controllers will result in injection of `TestModel` class instance.

>  it's seems to be broken

Please provide more info 😉

**Comment by hellraisercenobit** [comment]
@19majkel94 thx!
I have already tried with your approach (with and without service decorator).
I'll try again to give you more feedback on this with a real sample.

Now my tests working like a charm (i don't use Container anymore and supertest), but i'm curious to now why my old overrides was broken.

It's a good feature, so i'm really frustrated with that and you are right i don't need to mock expressApp entirely but it should work ;)

**Comment by pleerock** [comment]
Looks like a resolved issue, thanks @19majkel94 for the help!
