### ISSUE TITLE
register service with token and @Service(Token)

### ISSUE THREAD

**Issue by flensrocker** [typestack/typedi#55]
In the `sample8-tokenized-services` the services are registered via `Container.set`. I tried it with a `@Service(StoreService)` decorator at `FtpStore`, but that don't work.

Shouldn't I be able to register services with a token via a decorator like stated in the readme?

https://github.com/typestack/typedi#services-with-token-name

`ServiceNotFoundError: Service with a given token was not found, looks like it was not registered in the container. Register it by calling Container.set before using service.`

**Comment by flensrocker** [comment]
I think the cause lies in the typescript compiler. If I change `FtpReader.ts` to
```typescript
import {Reader} from "./Reader";
import {ReaderService} from "./Tokens";
import {Service} from "../../src/index";

@Service(ReaderService)
export class FtpReader implements Reader {
    read(): string {
         return "read from ftp";
    }
}
```
and comment the `Container.set(ReaderService, new FtpReader());` in `app.ts` then `app.js` looks like
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
var index_1 = require("../../src/index");
var Tokens_1 = require("./Tokens");
var FtpStore_1 = require("./FtpStore");
index_1.Container.set(Tokens_1.StoreService, new FtpStore_1.FtpStore());
// Container.set(ReaderService, new FtpReader());
var store = index_1.Container.get(Tokens_1.StoreService);
console.log(store.save());
var reader = index_1.Container.get(Tokens_1.ReaderService);
console.log(reader.read());
//# sourceMappingURL=app.js.map
```
so `FtpReader` is not imported and the decorator not executed. Then the service to the token cannot be found.

It can be fixed with an `import "./FtpReader"`, so tsc don't remove the `require`. Hm, have to think about it... Any hints are welcome.

**Comment by pleerock** [comment]
typescript compiler does not emit imports that are not needed in runtime. So, for example if you simply do `let reader: FtpReader = {}` you'll have FtpReader imported in your ts file, but you won't have it inside outputed file since its not used in runtime. 

Solution is to import as you wrote. You can also use `Container.import` method which does nothing inside, but when you use it values are being passed into function in runtime, thus your imports will be emitted into javascript code.

I think this can be closed.
