### ISSUE TITLE
Scoped container creates new instance of service every time

### ISSUE THREAD

**Issue by pepakriz** [typestack/typedi#61]
I've code:

```ts
@Service()
class Car {
    public serial = Math.random();
}

console.log(
    Container.of({}).get(Car).serial === Container.of({}).get(Car).serial,
); // false given
```

But I expect true.

I know, there is global service option, but I don't want to have one instance across all containers. I want to have one instance per every scoped container.

**Comment by pepakriz** [comment]
@pleerock Could you look at this, please? PR https://github.com/typestack/typedi/pull/62 works properly and I use it for a long time in my project.

**Comment by Nagato-Yuki** [comment]
This would break the actual behavior that many of people rely on it, such as maintaining state of service in the scope of HTTP request to prevent leaking of information across requests. So if you want one instance across scoped container, please consider to use global service option.

**Comment by pepakriz** [comment]
@Nagato-Yuki As I said, global service is shared across all containers. I want one instance per container.

> ...maintaining state of service in the scope of HTTP request to prevent leaking of information across requests

Yeah, it is exactly my use-case. I want to create nested container for each request to prevent sharing data. But actually, I can't use this feature, because `.get()` method returns new instance every time, which makes no sense.

**Comment by Nagato-Yuki** [comment]
I use this feature in my project without this issue. The scoped container return the same instance whenever I call `.get()`. It's depend on how you choose the identifier of your container.

Let's take a look to your code, because each `{}` is not the same instance, so it should be considered as unique identifier because it is ambiguous that 2 instances which are identical in their contents are intentionally or accidentally match.

So when you get `Container.of({}).get(Car).serial === Container.of({}).get(Car).serial`, it should be false because `Car` instance is from 2 different containers. Trying to break this would be dangerous.

I haven't face this problem because I use request id, which is generated UUID string, as container identifier so same string should be equal when compare with ===.

**Comment by Nagato-Yuki** [comment]
I use this feature in my project without this issue. The scoped container return the same instance whenever I call `.get()`. It's depend on how you choose the identifier of your container.

Let's take a look to your code, because each `{}` is not the same instance, so it should be considered as unique identifier because it is ambiguous that 2 instances which are identical in their contents are intentionally or accidentally match.

So when you get `Container.of({}).get(Car).serial === Container.of({}).get(Car).serial`, it should be false because you get `Car` instances from 2 different containers to compare their `serial`. Trying to break this would be dangerous.

I haven't face this problem because I use request id, which is generated UUID string, as container identifier for each request so same string should be equal when compare with `===`, that's why.

**Comment by pleerock** [comment]
Looks like there is an issue. Thanks @pepakriz for investigation and for the fix.

@Nagato-Yuki I added extra test

```ts
        (Container.of({}).get(Car).serial === Container.of({}).get(Car).serial).should.be.false;
```

and it passes with @pepakriz changes.
