### ISSUE TITLE
Simple question about how to expose external "require" as services

### ISSUE THREAD

**Issue by gremo** [typestack/typedi#65]
```
npm install bcryptjs --save
npm install @types/bcryptjs --save
```

I'd like to expose the bcryptjs utility as a service. Is this possible? Right now i'm using:

`import * as bcrypt from 'bcryptjs'`

... in my controller, but this doesn't feel "right". The same for other external libraries.

Thanks so much.

**Comment by pleerock** [comment]
>  but this doesn't feel "right"

I see you have a non-javascript background that's why it does not feel right to you. But its natural in javascript (it does not mean its bad, it just have such design, and its a good design in terms of language concept). 

In JavaScript you even don't need a service container, you can mock everything without it. But in my opinion service containers like typedi provides some really useful features additional to exist awesome javascript features, that's why I think its good to use typedi 😆 

What I can suggest is to either mock any required dependency using testing tools/utilities (google them), either do it using typedi [this way](https://github.com/typestack/typedi/tree/master/sample/sample14-external-imports).

**Comment by gremo** [comment]
@pleerock yes, you are right: I'm a PHP programmer (mainly). Thank you for your answer. If I get it right, you are saying: use external modules like you normally do since it's not a bad practice in JavaScript. But then, why using typedi at all? It seems to me a "mixed" way of work: mix services created with `@Service` annotation but use `require` for external modules. That's why I said that "It doesn't feel right" to me.

**Comment by pleerock** [comment]
mixing imports and services is okay I think. The main question is how are you going to mock them. And I told you solutions above... Probably what to choose is up to you

**Comment by Stradivario** [comment]
The reason is that you got Singleton pattern and you can inject same instances of services.
I think it is not a good idea to create singleton services for nodejs utility methods.You may not need this particular FS everywhere.So there is no point putting it inside Inversion control container of typedi.

Anyway you can check use case scenario for Typedi here:

https://github.com/Stradivario/gapi

It is a  GraphQL Api framework build on top of Typedi.
You can create such a configuration based on Angular 2 + pattern but writing Nodejs GraphQL API

```typescript
import { GapiModule, GapiModuleWithServices, InjectionToken } from '@gapi/core';

@Service()
export class MODULE_DI_CONFIG {
    text: string = 'Hello world';
}


const MY_MODULE_CONFIG = new InjectionToken<MODULE_DI_CONFIG>('my-module-config');


@GapiModule({
  imports: []
})
export class YourModule {
  public static forRoot(): GapiModuleWithServices {
    return {
      gapiModule: YourModule,
      services: [
          { provide: MY_MODULE_CONFIG, useValue: { text: 'Hello world' } },
          { provide: MY_MODULE_CONFIG, useClass: MODULE_DI_CONFIG },
          { 
            provide: MY_MODULE_CONFIG,
            useFactory: () => {
                return {text: 'Hello world'};
            }
          }
      ]
    }
  }
}
```

Regards,
Kristiyan Tachev

**Comment by NoNameProvided** [comment]
Closing as answered, if the issue persists please open a new issue with details.
