### ISSUE TITLE
fix: container get and getMany methods returns separate service instance

### ISSUE THREAD

**Issue by Luke265** [typestack/typedi#72]
I expected to receive the same instance of the service from both Container.get and Container.getMany methods, because I've set transient to false, but I get separate instances, see example below.

```ts
import { Container, Service, Token } from 'typedi';

const SharedToken = new Token<any>('test');

@Service({ id: SharedToken, multiple: true, transient: false })
class AService {
}
@Service({ id: SharedToken, multiple: true, transient: false })
class BService {
}

const aService = Container.get(AService);
const allServices = Container.getMany(SharedToken);

if (!allServices.find((service) => service === aService)) {
    console.error('Expected Container.get and Container.getMany to return the same AService instance');
}
```

Is this intended or a bug?

**Comment by NoNameProvided** [comment]
Cannot reproduce anymore. From `0.9.0` the above code will result in the following error:
```
Service with "MaybeConstructable<AService>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
```

This is the expected behavior. You registered your class with the ID `Token('test')`, so you cannot request it with the `AService` ID. Before 0.9.0 TypeDI always attempted to create an instance from the requested class if possible, but this behavior has been removed, thus we see the error now.
