### ISSUE TITLE
Factory to bind external library class

### ISSUE THREAD

**Issue by jasperblues** [typestack/typedi#90]
Analogue: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/FactoryBean.html

```ts
@Service
export class FooFactory implements ServiceFactory<DatabaseDriver> {

    create(): DatabaseDriver {
        return new DatabaseDriver()
    }
}

@Service 
export class UserManager {

    constructor(readonly dbDriver: DatabaseDriver) {}

```

Because there is a factory that produces instance of `DatabaseDriver` the driver can be injected.

**Comment by jasperblues** [comment]
Accept a pull request for this? I could use this feature.

**Comment by NoNameProvided** [comment]
I don't think this should be included in TypeDI. As for any feature request coming from Java world: Java and JS have vastly different approaches for writing code due to the JS not being a typed language. 

I don't see the benefit in bringing all the boilerplate solutions from Java into JS where there is no need for it.

```ts
import { getConnection } from './your-code'

const databaseDriverToken = new Token<DatabaseDriver>('DatabaseDriver');
Container.set(databaseDriverToken, getConnection());
```
